### ISSUE TITLE
It's easier than Salo thinks to nitpick at this code

### ISSUE THREAD

**Issue by the872** [jthompson18/COMP330#4]
To start, I will sort of nitpick at your directory naming because nitpicking means looking for the small ([allegedly unimportant](http://www.oxforddictionaries.com/us/definition/american_english/nitpicking)) issues. It makes sense on how you got to 'messager' (vs. messenger) but something tells me that it could have been a typo. However, we are all artists in our own way so I will accept that this was actually your intention and in the grand scale of things, is not a big deal either way. 

Regarding the re lib, we certainly agreed on some things #teamfindall() but I would argue that you should compile your regexs when you declare them. This is for a couple reasons: 
1. From my understanding it is not very time/data consuming to do so, especially on a project of this size.
2. It allows for your regex to be readily available to use, especially if it is used in more that one case.

**Comment by jthompson18** [comment]
@the872 If I claim its not a typo would you believe me? (It totally is, that's what I get for using a plain text editor).
As for our critique on my use of re.compile():
[Some say you don't even need it](http://stackoverflow.com/questions/452104/is-it-worth-using-pythons-re-compile). I might actually get rid of them completely. Honestly, I just learned of this stackoverflow issue and I was under the impression that re.compile was more important than it really was. My reason for placing re.compile() before using re.findall() was that I had contemplated allowing a third arg to be passed to the private functions that would extend the regex is some way or set a param on the regex getting compiled (for example IGNORECASE). I never went back and refactored it to move the re.compile() statements back to **init**(). But like that stackoverflow post suggests they probably aren't needed at all. @the872 feel free to fork this repo and update this if you'd like (and the typo).

**Comment by jthompson18** [comment]
@the872 I went ahead and made those changes. Thanks for the constructive input!

**Comment by the872** [comment]
Nice! Looks good from my end. 

Following up with the optional compiling, it is true that it's really there for the sake of fine-tuning the regex mostly. [Check out the first module, last paragraph](https://docs.python.org/2/library/re.html) which states: 

"It is important to note that most regular expression operations are available as module-level functions and RegexObject methods. The functions are shortcuts that don’t require you to compile a regex object first, but miss some fine-tuning parameters." 

Nice catch on that.
